# Generated by Django 5.2.5 on 2025-08-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
