# Generated by Django 5.2.5 on 2025-08-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_nomination_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nominator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
