# Generated by Django 5.2.5 on 2025-08-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_nomination_nominator_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='created_by',
            new_name='nominated_by',
        ),
    ]
