# Generated by Django 5.2.5 on 2025-08-24 19:32

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_alter_hero_options_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hero', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.CreateModel(
            name='HistoricalNomination',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_email', models.CharField(blank=True, null=True)),
                ('nominee_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('nominee_location', models.CharField(blank=True, max_length=255, null=True)),
                ('nominator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nominator_email', models.CharField(blank=True, null=True)),
                ('nominator_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('nominator_location', models.CharField(blank=True, max_length=255, null=True)),
                ('story', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('contact_status', models.CharField(choices=[('not_contacted', 'Not Contacted'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interview_scheduled', 'Interview Scheduled'), ('completed', 'Completed')], default='not_contacted', max_length=20)),
                ('contact_notes', models.TextField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nominated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nomination',
                'verbose_name_plural': 'historical nominations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
