# Generated by Django 5.2.5 on 2025-08-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0008_historicalstory_delete_historicalnomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='heroes.story'),
        ),
    ]
