# Generated by Django 5.2.5 on 2025-08-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_interview_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
