# Generated by Django 5.2.5 on 2025-08-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0010_interview_hero_alter_hero_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='interview_date',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='contact_notes',
        ),
    ]
