# Generated by Django 5.2.5 on 2025-08-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0013_alter_interview_options_historicalstory_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstory',
            name='cover_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories_cover/'),
        ),
        migrations.AlterField(
            model_name='historicalstory',
            name='intro',
            field=models.TextField(blank=True, help_text='Short summary for story previews', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='intro',
            field=models.TextField(blank=True, help_text='Short summary for story previews', null=True),
        ),
    ]
