# Generated by Django 5.2.5 on 2025-08-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0014_historicalstory_cover_image_story_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='image',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='unsungstories_cover/'),
        ),
    ]
