# Generated by Django 5.2.5 on 2025-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0015_rename_image_hero_avatar_alter_story_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('archieved', 'Archieved'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
