# Generated by Django 5.2.5 on 2025-08-25 22:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0017_alter_hero_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstory',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
