# Generated by Django 5.2.5 on 2025-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0018_alter_historicalstory_id_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstory',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
