# Generated by Django 5.2.5 on 2025-08-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0019_alter_historicalstory_id_alter_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstory',
            name='hero_quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='hero_quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
