# Generated by Django 5.2.5 on 2025-08-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0020_historicalstory_hero_quote_story_hero_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstory',
            name='top_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='top_story',
            field=models.BooleanField(default=False),
        ),
    ]
