# Generated by Django 5.2.5 on 2025-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0021_historicalstory_top_story_story_top_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstory',
            name='impact_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='impact_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
